// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
            'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      /*case TargetPlatform.iOS:
        return ios;*/
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCZRCkNPqysXkG56-IqWrHOdycaeU9ohk',
    appId: '1:335983895135:android:36b9716dafd5755f5eb1ea',
    messagingSenderId: '335983895135',
    projectId: 'news-dekho-4ab51',
    storageBucket: 'news-dekho-4ab51.appspot.com',
  );

 /* static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCP8lr38nQqv0l7QWlhfTaxsUKearLksHk',
    appId: '1:920385720556:ios:9f9a2fc55d4c51181d95c9',
    messagingSenderId: '920385720556',
    projectId: 'digital-interactive-coc',
    storageBucket: 'digital-interactive-coc.appspot.com',
    iosClientId: '920385720556-i5mk80tnigk8sp7qq7c9gmq1io6rv2p2.apps.googleusercontent.com',
    iosBundleId: 'com.coforge.iconf',
  );*/
}
